version: "3.5"
services:



  sheba_rilac_pms_admin_service:
    container_name: sheba_rilac_pms_admin_service
    image: rosebaysystems/pms_admin_service_sheba_rilac:12
    hostname: sheba_rilac_pms_admin_service
    ports:
      - 5041:5001
    volumes:
      # - /home/ubuntu/demo-env/sheba_rilac_pms_admin_service/.env.enc:/nestjs_core/.env.enc
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

networks:
  rilac_network:
    name: rilac-deployment-automation_default
    driver: bridge
