
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const DATABASE_CONNECTION = 'DATABASE_CONNECTION'
export const REDIS_CONNECTION = 'REDIS_CONNECTION';

export const TESTING_REPOSITORY = 'TESTING_REPOSITORY'


export const VOUCHER_REPOSITORY = 'VOUCHER_REPOSITORY'
export const VOUCHERTEMP_REPOSITORY = 'VOUCHERTEMP_REPOSITORY'
export const VOUCHERHISTORY_REPOSITORY = 'VOUCHERHISTORY_REPOSITORY'

export const PMSPOINTRULEVIEW_REPOSITORY = 'PMSPOINTRULEVIEW_REPOSITORY'
export const PMSPOINTRULEMAPVIEW_REPOSITORY = 'PMSPOINTRULEMAPVIEW_REPOSITORY'

export const PMSPOINTRULETEMPVIEW_REPOSITORY = 'PMSPOINTRULETEMPVIEW_REPOSITORY'
export const PMSPOINTRULEMAPTEMPVIEW_REPOSITORY = 'PMSPOINTRULEMAPTEMPVIEW_REPOSITORY'
